<?php

namespace Mediashare\ReferencingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReferencingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferencingRepository extends EntityRepository
{
}
