mediashare_script:
    resource: "@MediashareScriptBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_newsletter:
    resource: "@MediashareNewsletterBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_page:
    resource: "@MediasharePageBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_referencing:
    resource: "@MediashareReferencingBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_product:
    resource: "@MediashareProductBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_ged:
    resource: "@MediashareGedBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_faq:
    resource: "@MediashareFaqBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_gallery:
    resource: "@MediashareGalleryBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_news:
    resource: "@MediashareNewsBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_user:
    resource: "@MediashareUserBundle/Resources/config/routing.yml"
    prefix:   /

mediashare_admin:
    resource: "@MediashareAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

mediashare_app:
    resource: "@MediashareAppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mediashare_pdf:
    resource: "@MediasharePdfBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


# pageNotFound:
#     pattern:  /{path}
#     defaults: { _controller: MediashareAppBundle:Default:pageNotFound, path: '' }
#     requirements:
#         path: .*


# maintenance:
#     pattern:  /{path}
#     defaults: { _controller: MediashareAppBundle:Default:maintenance, path: '' }
#     requirements:
#         path: .*
