<?php

namespace Mediashare\NewsBundle\Entity;
use Mediashare\AdminBundle\Entity\PagerRepository;


/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class NewsRepository extends PagerRepository
{
}
