<?php

namespace Mediashare\FaqBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * faqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faqRepository extends EntityRepository
{
}
