admin_newsletter:
    path:     /
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:index" }

admin_newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:show" }

admin_newsletter_new:
    path:     /new
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:new" }

admin_newsletter_create:
    path:     /create
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:create" }
    methods:  POST

admin_newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:edit" }

admin_newsletter_update:
    path:     /{id}/update
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:update" }
    methods:  [POST, PUT]

admin_newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediashareNewsletterBundle:Newsletter:delete" }
    methods:  [POST, DELETE]
