admin_menu:
    path:     /
    defaults: { _controller: "MediashareAdminBundle:Menu:index" }

admin_menu_show:
    path:     /{id}/show
    defaults: { _controller: "MediashareAdminBundle:Menu:show" }

admin_menu_new:
    path:     /new
    defaults: { _controller: "MediashareAdminBundle:Menu:new" }

admin_menu_create:
    path:     /create
    defaults: { _controller: "MediashareAdminBundle:Menu:create" }
    methods:  POST

admin_menu_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediashareAdminBundle:Menu:edit" }

admin_menu_update:
    path:     /{id}/update
    defaults: { _controller: "MediashareAdminBundle:Menu:update" }
    methods:  [POST, PUT]

admin_menu_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediashareAdminBundle:Menu:delete" }
    methods:  [POST, DELETE]

admin_menu_submenu:
    path:     /submenu/{id}
    defaults: { _controller: "MediashareAdminBundle:Menu:subMenu" }
    methods:  [GET]
