<?php

namespace Mediashare\PdfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfRepository extends EntityRepository
{
}
