admin_keywords:
    path:     /
    defaults: { _controller: "MediashareReferencingBundle:Keywords:index" }

admin_keywords_new:
    path:     /new
    defaults: { _controller: "MediashareReferencingBundle:Keywords:new" }

admin_keywords_create:
    path:     /create
    defaults: { _controller: "MediashareReferencingBundle:Keywords:create" }
    methods:  POST

admin_keywords_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediashareReferencingBundle:Keywords:edit" }

admin_keywords_update:
    path:     /{id}/update
    defaults: { _controller: "MediashareReferencingBundle:Keywords:update" }
    methods:  [POST, PUT]

admin_keywords_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediashareReferencingBundle:Keywords:delete" }
    methods:  [POST, DELETE]
