admin_user:
    path:     /
    defaults: { _controller: "MediashareUserBundle:User:index" }

admin_user_show:
    path:     /{id}/show
    defaults: { _controller: "MediashareUserBundle:User:show" }

admin_user_new:
    path:     /new
    defaults: { _controller: "MediashareUserBundle:User:new" }

admin_user_create:
    path:     /create
    defaults: { _controller: "MediashareUserBundle:User:create" }
    methods:  POST

admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediashareUserBundle:User:edit" }

admin_user_update:
    path:     /{id}/update
    defaults: { _controller: "MediashareUserBundle:User:update" }
    methods:  [POST, PUT]

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediashareUserBundle:User:delete" }
    methods:  [POST, DELETE]
