admin_folder:
    path:     /
    defaults: { _controller: "MediashareGedBundle:Folder:index" }

admin_folder_show:
    path:     /{id}/show
    defaults: { _controller: "MediashareGedBundle:Folder:show" }

admin_folder_new:
    path:     /new
    defaults: { _controller: "MediashareGedBundle:Folder:new" }

admin_folder_create:
    path:     /create
    defaults: { _controller: "MediashareGedBundle:Folder:create" }
    methods:  POST

admin_folder_edit:
    path:     /{id}/edit
    defaults: { _controller: "MediashareGedBundle:Folder:edit" }

admin_folder_update:
    path:     /{id}/update
    defaults: { _controller: "MediashareGedBundle:Folder:update" }
    methods:  [POST, PUT]

admin_folder_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediashareGedBundle:Folder:delete" }
    methods:  [POST, DELETE]

admin_folder_sort:
    path:     /{id}/sort
    defaults: { _controller: "MediashareGedBundle:Folder:sort" }
